.PHONY: check validate test release release-sample sizes

check:
	node ./src/cli.js validate
	node ./src/test-domain-parsing.js

validate:
	node ./src/cli.js validate

test:
	node ./src/test-domain-parsing.js

release:
	node ./src/cli.js release

release-sample:
	node ./src/cli.js release-sample

sizes:
	node ./src/cli.js sizes
